# Generated by Django 2.2.6 on 2019-10-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
